### ISSUE TITLE
ffmpeg-light install issue (lzma)

### ISSUE THREAD

**Issue by akegalj** [acowley/ffmpeg-light#11]
ubuntu 14.04
ghc 7.8.4
cabal 1.22
lzma 9.22
```
$ cabal install ffmpeg-light
...
...
Configuring ffmpeg-light-0.8.1...
cabal: Missing dependency on a foreign library:
* Missing C library: lzma
This problem can usually be solved by installing the system package that
provides this library (you may need the "-dev" version). If the library is
already installed but in a non-standard location then you can use the flags
--extra-include-dirs= and --extra-lib-dirs= to specify where it is.
Failed to install ffmpeg-light-0.8.1
cabal: Error: some packages failed to install:
ffmpeg-light-0.8.1 failed during the configure step. The exception was:
ExitFailure 1

$ whereis lzma
lzma: /usr/bin/lzma /usr/bin/X11/lzma /usr/include/lzma /usr/share/man/man1/lzma.1.gz

$ lzma
lzma        lzma_alone  lzmainfo   
```

There are some instructions about additional flags to cabal but I'm not sure how to use them. Is StackOverflow better place for this kind of issue?

**Comment by acowley** [comment]
This is an Ubuntu problem. You could try installing `lzma-dev` via `apt`. But the vagrant test environment included here in the repo doesn't refer to that, so I'm not certain. The most related dependency I had to install for the vagrant build was `zlib1g-dev`. Check out the vagrant setup script and Ubuntu setup script for compiling ffmpeg from source. They might point you in the right direction.

**Comment by akegalj** [comment]
Oh, I didn't see the vagrant file. I am setting up vagrant now.

**Comment by acowley** [comment]
To be clear, you shouldn't *have* to use vagrant. It's very useful for establishing a common baseline, though. If it works there, you should be able to get it to work on your main system.

**Comment by akegalj** [comment]
I've successfully built ffmpeg on my bare system by folowing ubuntu build commands. Thanks

**Comment by acowley** [comment]
That's great! If you learned anything that might be of use to others, I encourage you to mention it here or in a brief problem solving section we could add to a document somewhere in the repository (maybe the readme).

**Comment by akegalj** [comment]
I will contribute as much as I can. It would be great if these C dependencies could be integrated into cabal build script. The build in *.sh files is done globally (because it is supposed to be used in vagrant). I will add install section about installing on ubuntu, trying to localaze install (using sandbox and moving install dependencies into local directory).

**Comment by acowley** [comment]
I think integrating the ffmpeg build is going too far. For a few years now, installing on OS X has been very nicely handled with just `brew install ffmpeg`. I understand that ffmpeg will be re-entering Ubuntu's apt collection soon if it hasn't already, so things should get much better there, too.
