### ISSUE TITLE
ResterDemo build

### ISSUE THREAD

**Issue by akegalj** [acowley/ffmpeg-light#12]
How can I build RasterDemo?

If I configure it like `PKG_CONFIG_PATH="$DIR/ffmpeg_build/lib/pkgconfig" cabal configure --disable-shared -fBuildRasterDemo` it claims

```
cabal: At least the following dependencies are missing:
Rasterific >=0.3
```

but after `cabal build` it builds first example (-fBuildDemo)

**Comment by acowley** [comment]
`cabal install --dependencies-only -f BuildRasterDemo` will, I think, get the dependencies sorted.

**Comment by akegalj** [comment]
```
Loading package text-1.2.0.4 ... <command line>: can't load .so/.DLL for: libHStext-1.2.0.4.so (libHStext-1.2.0.4.so: cannot open shared object file: No such file or directory)
Failed to install profunctors-4.3.2
cabal: Error: some packages failed to install:
Rasterific-0.5.0.3 depends on profunctors-4.3.2 which failed to install.
```
It looks something like [ghc bug](https://ghc.haskell.org/trac/ghc/ticket/8618) but maybe I messed something up.
I am trying force reinstalls now.

**Comment by ivanperez-keera** [comment]
Is this still an issue? Builds fine for me.

**Comment by akegalj** [comment]
Not an issue any more. Thanks for heads up. Closing
