### ISSUE TITLE
frameReaderTime giving wrong timestamps

### ISSUE THREAD

**Issue by noughtmare** [acowley/ffmpeg-light#17]
frameReaderTime is giving the wrong timestamps for some H.264 videos. I think this is the case because it is getting the time_base from the AVCodecContext. The time_base of the AVStream seems to give me the correct values. Is there a way to fix this?

**Comment by acowley** [comment]
Probably! I'm not at a computer right now, but if you can see where to pull it out of the stream, I'd be happy to accept a fix!

**Comment by noughtmare** [comment]
I would export the AVStream in the findVideoStream function. 
The type of the function findVideoStream would then become:
findVideoStream :: (MonadIO m, MonadError String m) => AVFormat -> m (CInt, AVCodecContext, AVCodec, AVStream)
Then the AVStream can be used instead of the AVCodecContext to find the numerator and denominator of the inverse framerate. like this:
AVRational num den <- liftIO $ getTimeBase vidStream

**Comment by acowley** [comment]
@noughtmare Can you check that the `StreamTime` branch addresses the issue you encountered?

**Comment by noughtmare** [comment]
Yes, that solves the issue.
