### ISSUE TITLE
First frame of video is not at time zero, resulting in initial "black frame"

### ISSUE THREAD

**Issue by jtdaugherty** [acowley/ffmpeg-light#18]
I'm creating movie files by emitting frames using `imageWriter` in `ffmpeg-light`version `0.9`, `ffmpeg` version `2.8.1_1` installed via Homebrew, and GHC `7.10.2`.  When I play movies generated this way, the first frame appears to be black.  Digging in a bit more using the approach suggested at http://superuser.com/a/559205, I ran `ffprobe -show_frames` on the video and I see this for the first frame:
```
[FRAME]
media_type=video
stream_index=0
key_frame=1
pkt_pts=507
pkt_pts_time=0.033008
pkt_dts=507
pkt_dts_time=0.033008
best_effort_timestamp=507
best_effort_timestamp_time=0.033008
...
```
This seems to suggest the reason for the apparent "black frame" is because the first frame I output gets put at time `0.033008` rather than `0.0` (which is what I see when I inspect a few videos I have from other sources that don't suffer from this problem).

I'm using `defaultParams` to set up `imageWriter`.  Here's some info on my installation:
```
$ ffmpeg
ffmpeg version 2.8.1 Copyright (c) 2000-2015 the FFmpeg developers
  built with Apple LLVM version 7.0.0 (clang-700.0.72)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/2.8.1_1 --enable-shared --enable-pthreads --enable-gpl --enable-version3 --enable-hardcoded-tables --enable-avresample --cc=clang --host-cflags= --host-ldflags= --enable-opencl --enable-libx264 --enable-libmp3lame --enable-libvo-aacenc --enable-libxvid --enable-vda
  libavutil      54. 31.100 / 54. 31.100
  libavcodec     56. 60.100 / 56. 60.100
  libavformat    56. 40.101 / 56. 40.101
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 40.101 /  5. 40.101
  libavresample   2.  1.  0 /  2.  1.  0
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  2.101 /  1.  2.101
  libpostproc    53.  3.100 / 53.  3.100
```

**Comment by jtdaugherty** [comment]
(For what it's worth, I know very little about video encoding so I don't know whether this is truly problematic, but it seems to be related to what I'm seeing.)

**Comment by jtdaugherty** [comment]
Thanks for merging this! Would it be possible to get a bugfix release on Hackage containing this change?

**Comment by acowley** [comment]
Done! Thanks again for the fix.

**Comment by jtdaugherty** [comment]
You're welcome. I tried `0.10` and the generated movies look great. Thanks!
