### ISSUE TITLE
Support ffmpeg 3.x

### ISSUE THREAD

**Issue by TomMD** [acowley/ffmpeg-light#26]
The new 3.x version has been released with much API breakage (stated up front at release time, I haven't looked myself).  Eventually, after many package systems have moved to including 3.x, we should update this package to the new API.

**Comment by acowley** [comment]
Thanks for opening the issue! I looked at the change log the other day and didn't see anything that would obviously break basic usage, but I haven't looked at the API yet. I hope it's not a big split for us as it would be pretty hard to maintain support for two divergent APIs.

**Comment by waldheinz** [comment]
The `nameCompat.h` stuff seems to cause breakage with FFmpeg 3. It gets erroneously included from `Enums.hsc` (the "fragile" old version check at the top of the file), and then it goes havoc. Simply removing the `#include` fixed it for me.

**Comment by acowley** [comment]
The version on `master` seems to work with ffmpeg-3.0 for me on OS X. Can anyone else confirm?

**Comment by TomMD** [comment]
It builds for me and can run `./demo/Main cam` properly.

**Comment by waldheinz** [comment]
For me it builds and runs on 
  * Arch Linux (FFmpeg 3.0, GHC 7.10.3) and
  * FreeBSD (FFmpeg 2.7.2, GHC 7.10.2)

And that's all I care about. :-)
