### ISSUE TITLE
use of deprecated Control.Monad.Error

### ISSUE THREAD

**Issue by AleXoundOS** [acowley/ffmpeg-light#31]
In fact ffmpeg-light uses not [Control.Monad.Error](https://hackage.haskell.org/package/mtl-2.2.1/docs/Control-Monad-Error.html) directly, but [Control.Monad.Error.Class](https://hackage.haskell.org/package/mtl-2.2.1/docs/Control-Monad-Error-Class.html). But it seems obvious that nested [Control.Monad.Error.Class](https://hackage.haskell.org/package/mtl-2.2.1/docs/Control-Monad-Error-Class.html) is deprecated as well. [Control.Monad.Except](https://hackage.haskell.org/package/mtl-2.2.1/docs/Control-Monad-Except.html) seems to provide same functionality.

From [Control.Monad.Error](https://hackage.haskell.org/package/mtl-2.2.1/docs/Control-Monad-Error.html) docs page:

> Deprecated: Use Control.Monad.Except instead

**Comment by acowley** [comment]
Thanks for the report!
