### ISSUE TITLE
package `either` dropped 'Control.Monad.Trans.Either' 

### ISSUE THREAD

**Issue by fabricatedmath** [acowley/ffmpeg-light#39]
```Control.Monad.Trans.Either``` was dropped in the package either-5 in favor of ```Control.Monad.Trans.Except``` in transformers. Noticed this because latest stackage moved from either-4.5 to either-5 and got the compile error.

Comments from drop:
https://github.com/ekmett/either/commit/543f78bce4bcd8131318b912574d409f59ce6144

Just a heads up!

**Comment by acowley** [comment]
Thanks for letting me know!

Does that commit hit the only place we were using the `Either` transformer? I only did a quick grep.

**Comment by fabricatedmath** [comment]
Looks like it, builds on the latest commit!

Thanks!
