### ISSUE TITLE
Use av_strerror for FFmpeg error messages?

### ISSUE THREAD

**Issue by owickstrom** [acowley/ffmpeg-light#42]
Hi! First of all, thanks for the library! I've just started using it to process and chop up videos and it's working nicely so far.

I had some trouble opening files and the error message thrown by [`readFile`](https://github.com/acowley/ffmpeg-light/blob/8a29f67c0a0348f79afa7d73f8e70ebe5d92fedc/src/Codec/FFmpeg/Decode.hs#L103-L110) isn't very helpful. As seen in the following error message, it prints the numeric error code.

```
*** Exception: user error (ffmpeg failed opening file: -1094995529)
CallStack (from HasCallStack):
  error, called at src/Codec/FFmpeg/Juicy.hs:128:27 in ffmpeg-light-0.12.1.0-cf5adea21c23b3bea23fc219b84d9eaa2476dc02798ac7442955da596dc4c1b2:Codec.FFmpeg.Juicy
```

Do you think `ffmpeg-light` and the `openFile` function could use the [`av_strerror`](https://www.ffmpeg.org/doxygen/2.3/group__lavu__error.html#ga5792b4a2d18d7d9cb0efbcfc335dce24) function in FFmpeg to map errors into strings? I could take a stab at sending a PR, but I'm not very experienced with C FFI in Haskell, so it might not be solid.

Thanks!

**Comment by acowley** [comment]
That is a terrific idea! Please do start a PR.
