### ISSUE TITLE
The documentation for the latest version of this package is missing on Hackage. 

### ISSUE THREAD

**Issue by expipiplus1** [acowley/ffmpeg-light#56]
It's possible that Hackage wasn't able to build the package.

Is it possible for you to manually upload the package using `cabal upload --doc`, please? Note that this requires cabal-install >= 1.24

Thanks!

**Comment by charlescrain** [comment]
Second this!

**Comment by gelisam** [comment]
The first step is to figure out which commit to generate the docs from. I used `cabal get ffmpeg-light-0.12.2.2` and then compared (the hash of) its contents with a few recent commits in order to figure out which commit version 0.12.2.2 is based on, and I have tagged it with `0.12.2.2`.

**Comment by gelisam** [comment]
I have generated the docs locally and have confirmed that they look good. @acowley , if you give me write access on hackage as well, I can upload the docs for you.

**Comment by acowley** [comment]
Thank you @gelisam! I was quietly hoping we’d be cutting a release last week so I could handle the docs then. What is your hackage username?

**Comment by gelisam** [comment]
> What is your hackage username?

It's `gelisam`

**Comment by acowley** [comment]
Okay, I’ve added you on hackage. Thank you again!

**Comment by gelisam** [comment]
Thanks, the documentation for 0.12.2.2 is now up at https://hackage.haskell.org/package/ffmpeg-light-0.12.2.2

**Comment by expipiplus1** [comment]
Thanks!
