### ISSUE TITLE
publish new version to hackage

### ISSUE THREAD

**Issue by ukari** [acowley/ffmpeg-light#59]
In the hackage the ffmpeg-light package with version 0.12.2.2 has a dependency which need base (>=4.6 && <4.13), while now the newest base package has a verison 4.14.0.0.

links:
- [hackage ffmpeg-light](https://hackage.haskell.org/package/ffmpeg-light)
- [hackage base](https://hackage.haskell.org/package/base)
- [tag 0.12.2.2 ffmpeg-light.cabal dependencies](https://github.com/acowley/ffmpeg-light/blob/0.12.2.2/ffmpeg-light.cabal#L70)
- [master ffmpeg-light.cabal dependencies](https://github.com/acowley/ffmpeg-light/blob/be926431ee5aac57ca3e0f8064ba85efe756dd3f/ffmpeg-light.cabal#L70)

**Comment by acowley** [comment]
Thanks for reminding me! We've got a big [audio PR](https://github.com/acowley/ffmpeg-light/pull/53) that stalled, and a minor [webcam fix](https://github.com/DiegoNolan/ffmpeg-light/pull/1) that I built atop the WIP audio work. I'll see if we can land both in the next couple days. If not, then I'll pull the webcam fix back to the trunk version and cut a release from that.

**Comment by acowley** [comment]
Alright, I'm giving up on the audio branch for now as it seems the author doesn't have time to finish it off. I've uploaded a [candidate](https://hackage.haskell.org/package/ffmpeg-light-0.13.0/candidate) for version 0.13.

CI is green, but I'd like to hear of someone other than me able to build, and preferably run, this before I publish.

**Comment by gelisam** [comment]
Can you explain how to test a candidate release? I always upload a candidate before publishing a new release, but then at the "test the candidate" step I realize that I can't specify a candidate version to either cabal or stack, so I end up publishing and then testing the real release.

**Comment by acowley** [comment]
Huh, I had hoped that this was something that everyone other than me knew as I don't know how to use them either 😂.

I think you can use a [`cabal.project`](https://cabal.readthedocs.io/en/3.4/cabal-project.html) file with a [URL for the release candidate tar file](https://hackage.haskell.org/package/ffmpeg-light-0.13.0/candidate/ffmpeg-light-0.13.0.tar.gz). If you're already set up to use a local checkout or git repo directly, then there is [this branch](https://github.com/acowley/ffmpeg-light/tree/0.13).

**Comment by gelisam** [comment]
I compiled that branch using 8.10.1 and was able to run the demo successfully.

**Comment by acowley** [comment]
Thank you @gelisam!

I've pushed 0.13.0 to hackage! Thank you all for the patient reminders to do so.

**Comment by gelisam** [comment]
The documentation did not get built automatically, so I built and uploaded it.
